---
version: 2

project_name: mesh-manager

release:
  github:
    owner: USA-RedDragon
    name: mesh-manager
  skip_upload: true

dockers_v2:
  - images:
      - "ghcr.io/usa-reddragon/{{ .ProjectName }}"
    tags:
      - "{{ .Tag }}"
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - latest
    extra_files:
      - docker/rootfs
      - frontend
    labels:
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.licenses": AGPL-3.0-or-later
      "org.opencontainers.image.url": "https://github.com/USA-RedDragon/{{ .ProjectName }}"
      "org.opencontainers.image.source": "https://github.com/USA-RedDragon/{{ .ProjectName }}"

builds:
  - main: .
    binary: mesh-manager
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath

milestones:
  - close: true
