// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package config

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
	"fmt"
	configulator "github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/spf13/pflag"
	"math"
	"strconv"
	"strings"
)

type pProfShadow struct {
	Enabled *bool `json:"enabled" toml:"enabled" yaml:"enabled"`
}
type postgresShadow struct {
	Host     *string `json:"host" toml:"host" yaml:"host"`
	Port     *int    `json:"port" toml:"port" yaml:"port"`
	User     *string `json:"user" toml:"user" yaml:"user"`
	Password *string `json:"password" toml:"password" yaml:"password"`
	Database *string `json:"database" toml:"database" yaml:"database"`
}
type babelShadow struct {
	Enabled  *bool   `json:"enabled" toml:"enabled" yaml:"enabled"`
	RouterID *string `json:"router-id" toml:"router-id" yaml:"router-id"`
}
type metricsShadow struct {
	Enabled          *bool   `json:"enabled" toml:"enabled" yaml:"enabled"`
	NodeExporterHost *string `json:"node-exporter-host" toml:"node-exporter-host" yaml:"node-exporter-host"`
	Port             *int    `json:"port" toml:"port" yaml:"port"`
}
type wireguardShadow struct {
	StartingAddress *string `json:"starting-address" toml:"starting-address" yaml:"starting-address"`
	StartingPort    *uint16 `json:"starting-port" toml:"starting-port" yaml:"starting-port"`
}
type lQMShadow struct {
	Enabled *bool `json:"enabled" toml:"enabled" yaml:"enabled"`
}
type configShadow struct {
	LogLevel                 *string          `json:"log-level" toml:"log-level" yaml:"log-level"`
	Port                     *int             `json:"port" toml:"port" yaml:"port"`
	PasswordSalt             *string          `json:"password-salt" toml:"password-salt" yaml:"password-salt"`
	PProf                    *pProfShadow     `json:"pprof" toml:"pprof" yaml:"pprof"`
	Postgres                 *postgresShadow  `json:"postgres" toml:"postgres" yaml:"postgres"`
	InitialAdminUserPassword *string          `json:"initial-admin-user-password" toml:"initial-admin-user-password" yaml:"initial-admin-user-password"`
	Babel                    *babelShadow     `json:"babel" toml:"babel" yaml:"babel"`
	OLSR                     *bool            `json:"olsr" toml:"olsr" yaml:"olsr"`
	CORSHosts                *[]string        `json:"cors-hosts" toml:"cors-hosts" yaml:"cors-hosts"`
	TrustedProxies           *[]string        `json:"trusted-proxies" toml:"trusted-proxies" yaml:"trusted-proxies"`
	HIBPAPIKey               *string          `json:"hibp-api-key" toml:"hibp-api-key" yaml:"hibp-api-key"`
	ServerName               *string          `json:"server-name" toml:"server-name" yaml:"server-name"`
	Supernode                *bool            `json:"supernode" toml:"supernode" yaml:"supernode"`
	NodeIP                   *string          `json:"node-ip" toml:"node-ip" yaml:"node-ip"`
	Latitude                 *float64         `json:"latitude" toml:"latitude" yaml:"latitude"`
	Longitude                *float64         `json:"longitude" toml:"longitude" yaml:"longitude"`
	Gridsquare               *string          `json:"gridsquare" toml:"gridsquare" yaml:"gridsquare"`
	Metrics                  *metricsShadow   `json:"metrics" toml:"metrics" yaml:"metrics"`
	Wireguard                *wireguardShadow `json:"wireguard" toml:"wireguard" yaml:"wireguard"`
	SessionSecret            *string          `json:"session-secret" toml:"session-secret" yaml:"session-secret"`
	LQM                      *lQMShadow       `json:"lqm" toml:"lqm" yaml:"lqm"`
	Walker                   *bool            `json:"walker" toml:"walker" yaml:"walker"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}
func configApplyDefaults(cfg *Config, set configulator.SetOrigin) error {
	cfg.LogLevel = LogLevel("info")
	set("log-level", configulator.LayerDefault, "default tag")
	cfg.Port = 3333
	set("port", configulator.LayerDefault, "default tag")
	cfg.PProf.Enabled = false
	set("pprof.enabled", configulator.LayerDefault, "default tag")
	cfg.Postgres.Port = 5432
	set("postgres.port", configulator.LayerDefault, "default tag")
	cfg.Babel.Enabled = false
	set("babel.enabled", configulator.LayerDefault, "default tag")
	cfg.OLSR = true
	set("olsr", configulator.LayerDefault, "default tag")
	cfg.Metrics.NodeExporterHost = "node-exporter"
	set("metrics.node-exporter-host", configulator.LayerDefault, "default tag")
	cfg.Metrics.Port = 9100
	set("metrics.port", configulator.LayerDefault, "default tag")
	cfg.Wireguard.StartingPort = uint16(5527)
	set("wireguard.starting-port", configulator.LayerDefault, "default tag")
	cfg.LQM.Enabled = true
	set("lqm.enabled", configulator.LayerDefault, "default tag")
	cfg.Walker = false
	set("walker", configulator.LayerDefault, "default tag")
	return nil
}
func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, set, file)
}
func (s *configShadow) applyTo(cfg *Config, set configulator.SetOrigin, file string) error {
	if s.LogLevel != nil {
		cfg.LogLevel = LogLevel(*s.LogLevel)
		set("log-level", configulator.LayerFile, file)
	}
	if s.Port != nil {
		cfg.Port = *s.Port
		set("port", configulator.LayerFile, file)
	}
	if s.PasswordSalt != nil {
		cfg.PasswordSalt = *s.PasswordSalt
		set("password-salt", configulator.LayerFile, file)
	}
	if s.PProf != nil {
		if s.PProf.Enabled != nil {
			cfg.PProf.Enabled = *s.PProf.Enabled
			set("pprof.enabled", configulator.LayerFile, file)
		}
	}
	if s.Postgres != nil {
		if s.Postgres.Host != nil {
			cfg.Postgres.Host = *s.Postgres.Host
			set("postgres.host", configulator.LayerFile, file)
		}
		if s.Postgres.Port != nil {
			cfg.Postgres.Port = *s.Postgres.Port
			set("postgres.port", configulator.LayerFile, file)
		}
		if s.Postgres.User != nil {
			cfg.Postgres.User = *s.Postgres.User
			set("postgres.user", configulator.LayerFile, file)
		}
		if s.Postgres.Password != nil {
			cfg.Postgres.Password = *s.Postgres.Password
			set("postgres.password", configulator.LayerFile, file)
		}
		if s.Postgres.Database != nil {
			cfg.Postgres.Database = *s.Postgres.Database
			set("postgres.database", configulator.LayerFile, file)
		}
	}
	if s.InitialAdminUserPassword != nil {
		cfg.InitialAdminUserPassword = *s.InitialAdminUserPassword
		set("initial-admin-user-password", configulator.LayerFile, file)
	}
	if s.Babel != nil {
		if s.Babel.Enabled != nil {
			cfg.Babel.Enabled = *s.Babel.Enabled
			set("babel.enabled", configulator.LayerFile, file)
		}
		if s.Babel.RouterID != nil {
			cfg.Babel.RouterID = *s.Babel.RouterID
			set("babel.router-id", configulator.LayerFile, file)
		}
	}
	if s.OLSR != nil {
		cfg.OLSR = *s.OLSR
		set("olsr", configulator.LayerFile, file)
	}
	if s.CORSHosts != nil {
		cfg.CORSHosts = *s.CORSHosts
		set("cors-hosts", configulator.LayerFile, file)
	}
	if s.TrustedProxies != nil {
		cfg.TrustedProxies = *s.TrustedProxies
		set("trusted-proxies", configulator.LayerFile, file)
	}
	if s.HIBPAPIKey != nil {
		cfg.HIBPAPIKey = *s.HIBPAPIKey
		set("hibp-api-key", configulator.LayerFile, file)
	}
	if s.ServerName != nil {
		cfg.ServerName = *s.ServerName
		set("server-name", configulator.LayerFile, file)
	}
	if s.Supernode != nil {
		cfg.Supernode = *s.Supernode
		set("supernode", configulator.LayerFile, file)
	}
	if s.NodeIP != nil {
		cfg.NodeIP = *s.NodeIP
		set("node-ip", configulator.LayerFile, file)
	}
	if s.Latitude != nil {
		cfg.Latitude = *s.Latitude
		set("latitude", configulator.LayerFile, file)
	}
	if s.Longitude != nil {
		cfg.Longitude = *s.Longitude
		set("longitude", configulator.LayerFile, file)
	}
	if s.Gridsquare != nil {
		cfg.Gridsquare = *s.Gridsquare
		set("gridsquare", configulator.LayerFile, file)
	}
	if s.Metrics != nil {
		if s.Metrics.Enabled != nil {
			cfg.Metrics.Enabled = *s.Metrics.Enabled
			set("metrics.enabled", configulator.LayerFile, file)
		}
		if s.Metrics.NodeExporterHost != nil {
			cfg.Metrics.NodeExporterHost = *s.Metrics.NodeExporterHost
			set("metrics.node-exporter-host", configulator.LayerFile, file)
		}
		if s.Metrics.Port != nil {
			cfg.Metrics.Port = *s.Metrics.Port
			set("metrics.port", configulator.LayerFile, file)
		}
	}
	if s.Wireguard != nil {
		if s.Wireguard.StartingAddress != nil {
			cfg.Wireguard.StartingAddress = *s.Wireguard.StartingAddress
			set("wireguard.starting-address", configulator.LayerFile, file)
		}
		if s.Wireguard.StartingPort != nil {
			cfg.Wireguard.StartingPort = *s.Wireguard.StartingPort
			set("wireguard.starting-port", configulator.LayerFile, file)
		}
	}
	if s.SessionSecret != nil {
		cfg.SessionSecret = *s.SessionSecret
		set("session-secret", configulator.LayerFile, file)
	}
	if s.LQM != nil {
		if s.LQM.Enabled != nil {
			cfg.LQM.Enabled = *s.LQM.Enabled
			set("lqm.enabled", configulator.LayerFile, file)
		}
	}
	if s.Walker != nil {
		cfg.Walker = *s.Walker
		set("walker", configulator.LayerFile, file)
	}
	return nil
}
func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "log-level"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.LogLevel = LogLevel(v)
			set("log-level", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "port"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "port",
					Source: n,
					Value:  v,
				}
			}
			cfg.Port = int(p)
			set("port", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "password-salt"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.PasswordSalt = v
			set("password-salt", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "pprof", "enabled"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseBool(v)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "pprof.enabled",
					Source: n,
					Value:  v,
				}
			}
			cfg.PProf.Enabled = p
			set("pprof.enabled", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "postgres", "host"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Postgres.Host = v
			set("postgres.host", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "postgres", "port"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "postgres.port",
					Source: n,
					Value:  v,
				}
			}
			cfg.Postgres.Port = int(p)
			set("postgres.port", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "postgres", "user"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Postgres.User = v
			set("postgres.user", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "postgres", "password"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Postgres.Password = v
			set("postgres.password", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "postgres", "database"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Postgres.Database = v
			set("postgres.database", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "initial-admin-user-password"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.InitialAdminUserPassword = v
			set("initial-admin-user-password", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "babel", "enabled"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseBool(v)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "babel.enabled",
					Source: n,
					Value:  v,
				}
			}
			cfg.Babel.Enabled = p
			set("babel.enabled", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "babel", "router-id"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Babel.RouterID = v
			set("babel.router-id", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "olsr"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseBool(v)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "olsr",
					Source: n,
					Value:  v,
				}
			}
			cfg.OLSR = p
			set("olsr", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "cors-hosts"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.CORSHosts = configulator.SplitList(v, ec.ArraySeparator)
			set("cors-hosts", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "trusted-proxies"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.TrustedProxies = configulator.SplitList(v, ec.ArraySeparator)
			set("trusted-proxies", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "hibp-api-key"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.HIBPAPIKey = v
			set("hibp-api-key", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "server-name"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.ServerName = v
			set("server-name", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "supernode"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseBool(v)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "supernode",
					Source: n,
					Value:  v,
				}
			}
			cfg.Supernode = p
			set("supernode", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "node-ip"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.NodeIP = v
			set("node-ip", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "latitude"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseFloat(v, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "latitude",
					Source: n,
					Value:  v,
				}
			}
			cfg.Latitude = p
			set("latitude", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "longitude"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseFloat(v, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "longitude",
					Source: n,
					Value:  v,
				}
			}
			cfg.Longitude = p
			set("longitude", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "gridsquare"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Gridsquare = v
			set("gridsquare", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "metrics", "enabled"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseBool(v)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "metrics.enabled",
					Source: n,
					Value:  v,
				}
			}
			cfg.Metrics.Enabled = p
			set("metrics.enabled", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "metrics", "node-exporter-host"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Metrics.NodeExporterHost = v
			set("metrics.node-exporter-host", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "metrics", "port"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "metrics.port",
					Source: n,
					Value:  v,
				}
			}
			cfg.Metrics.Port = int(p)
			set("metrics.port", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "wireguard", "starting-address"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Wireguard.StartingAddress = v
			set("wireguard.starting-address", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "wireguard", "starting-port"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseUint(v, 10, 16)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "wireguard.starting-port",
					Source: n,
					Value:  v,
				}
			}
			cfg.Wireguard.StartingPort = uint16(p)
			set("wireguard.starting-port", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "session-secret"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.SessionSecret = v
			set("session-secret", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "lqm", "enabled"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseBool(v)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "lqm.enabled",
					Source: n,
					Value:  v,
				}
			}
			cfg.LQM.Enabled = p
			set("lqm.enabled", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "walker"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseBool(v)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "walker",
					Source: n,
					Value:  v,
				}
			}
			cfg.Walker = p
			set("walker", configulator.LayerEnv, n)
		}
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}
func configRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	for _, name := range []string{strings.Join([]string{"log-level"}, o.Separator), strings.Join([]string{"port"}, o.Separator), strings.Join([]string{"password-salt"}, o.Separator), strings.Join([]string{"pprof", "enabled"}, o.Separator), strings.Join([]string{"postgres", "host"}, o.Separator), strings.Join([]string{"postgres", "port"}, o.Separator), strings.Join([]string{"postgres", "user"}, o.Separator), strings.Join([]string{"postgres", "password"}, o.Separator), strings.Join([]string{"postgres", "database"}, o.Separator), strings.Join([]string{"initial-admin-user-password"}, o.Separator), strings.Join([]string{"babel", "enabled"}, o.Separator), strings.Join([]string{"babel", "router-id"}, o.Separator), strings.Join([]string{"olsr"}, o.Separator), strings.Join([]string{"cors-hosts"}, o.Separator), strings.Join([]string{"trusted-proxies"}, o.Separator), strings.Join([]string{"hibp-api-key"}, o.Separator), strings.Join([]string{"server-name"}, o.Separator), strings.Join([]string{"supernode"}, o.Separator), strings.Join([]string{"node-ip"}, o.Separator), strings.Join([]string{"latitude"}, o.Separator), strings.Join([]string{"longitude"}, o.Separator), strings.Join([]string{"gridsquare"}, o.Separator), strings.Join([]string{"metrics", "enabled"}, o.Separator), strings.Join([]string{"metrics", "node-exporter-host"}, o.Separator), strings.Join([]string{"metrics", "port"}, o.Separator), strings.Join([]string{"wireguard", "starting-address"}, o.Separator), strings.Join([]string{"wireguard", "starting-port"}, o.Separator), strings.Join([]string{"session-secret"}, o.Separator), strings.Join([]string{"lqm", "enabled"}, o.Separator), strings.Join([]string{"walker"}, o.Separator)} {
		if fs.Lookup(name) != nil {
			return fmt.Errorf("flag --%s already registered on this FlagSet", name)
		}
	}
	fs.String(strings.Join([]string{"log-level"}, o.Separator), "info", "Logging level for the application. One of debug, info, warn, or error")
	fs.Int(strings.Join([]string{"port"}, o.Separator), 3333, "Port to listen on for HTTP requests")
	fs.String(strings.Join([]string{"password-salt"}, o.Separator), "", "Salt used for password hashing")
	fs.Bool(strings.Join([]string{"pprof", "enabled"}, o.Separator), false, "Enable pprof debugging")
	fs.String(strings.Join([]string{"postgres", "host"}, o.Separator), "", "PostgreSQL host")
	fs.Int(strings.Join([]string{"postgres", "port"}, o.Separator), 5432, "PostgreSQL port")
	fs.String(strings.Join([]string{"postgres", "user"}, o.Separator), "", "PostgreSQL user")
	fs.String(strings.Join([]string{"postgres", "password"}, o.Separator), "", "PostgreSQL password")
	fs.String(strings.Join([]string{"postgres", "database"}, o.Separator), "", "PostgreSQL database")
	fs.String(strings.Join([]string{"initial-admin-user-password"}, o.Separator), "", "Initial password for the admin user")
	fs.Bool(strings.Join([]string{"babel", "enabled"}, o.Separator), false, "Enable Babel routing")
	fs.String(strings.Join([]string{"babel", "router-id"}, o.Separator), "", "Babel router ID")
	fs.Bool(strings.Join([]string{"olsr"}, o.Separator), true, "Enable OLSR routing")
	fs.StringSlice(strings.Join([]string{"cors-hosts"}, o.Separator), nil, "CORS hosts for the API")
	fs.StringSlice(strings.Join([]string{"trusted-proxies"}, o.Separator), nil, "Trusted proxies for the API")
	fs.String(strings.Join([]string{"hibp-api-key"}, o.Separator), "", "Have I Been Pwned API key")
	fs.String(strings.Join([]string{"server-name"}, o.Separator), "", "Server name")
	fs.Bool(strings.Join([]string{"supernode"}, o.Separator), false, "Enable supernode mode")
	fs.String(strings.Join([]string{"node-ip"}, o.Separator), "", "Node IP address")
	fs.Float64(strings.Join([]string{"latitude"}, o.Separator), 0.0, "Server latitude")
	fs.Float64(strings.Join([]string{"longitude"}, o.Separator), 0.0, "Server longitude")
	fs.String(strings.Join([]string{"gridsquare"}, o.Separator), "", "Server gridsquare")
	fs.Bool(strings.Join([]string{"metrics", "enabled"}, o.Separator), false, "Enable Prometheus metrics")
	fs.String(strings.Join([]string{"metrics", "node-exporter-host"}, o.Separator), "node-exporter", "Node exporter host for Prometheus metrics")
	fs.Int(strings.Join([]string{"metrics", "port"}, o.Separator), 9100, "Port for Prometheus metrics")
	fs.String(strings.Join([]string{"wireguard", "starting-address"}, o.Separator), "", "Starting address for Wireguard")
	fs.Uint16(strings.Join([]string{"wireguard", "starting-port"}, o.Separator), uint16(5527), "Starting port for Wireguard")
	fs.String(strings.Join([]string{"session-secret"}, o.Separator), "", "Session secret")
	fs.Bool(strings.Join([]string{"lqm", "enabled"}, o.Separator), true, "Enable Link Quality Monitoring")
	fs.Bool(strings.Join([]string{"walker"}, o.Separator), false, "Enable periodic mesh walking to update meshmap")
	return nil
}
func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, o *cpflag.Options, set configulator.SetOrigin) error {
	if n := strings.Join([]string{"log-level"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "log-level",
				Source: "--" + n,
			}
		}
		cfg.LogLevel = LogLevel(v)
		set("log-level", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"port"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "port",
				Source: "--" + n,
			}
		}
		cfg.Port = v
		set("port", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"password-salt"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "password-salt",
				Source: "--" + n,
			}
		}
		cfg.PasswordSalt = v
		set("password-salt", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"pprof", "enabled"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.enabled",
				Source: "--" + n,
			}
		}
		cfg.PProf.Enabled = v
		set("pprof.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"postgres", "host"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "postgres.host",
				Source: "--" + n,
			}
		}
		cfg.Postgres.Host = v
		set("postgres.host", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"postgres", "port"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "postgres.port",
				Source: "--" + n,
			}
		}
		cfg.Postgres.Port = v
		set("postgres.port", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"postgres", "user"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "postgres.user",
				Source: "--" + n,
			}
		}
		cfg.Postgres.User = v
		set("postgres.user", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"postgres", "password"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "postgres.password",
				Source: "--" + n,
			}
		}
		cfg.Postgres.Password = v
		set("postgres.password", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"postgres", "database"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "postgres.database",
				Source: "--" + n,
			}
		}
		cfg.Postgres.Database = v
		set("postgres.database", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"initial-admin-user-password"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "initial-admin-user-password",
				Source: "--" + n,
			}
		}
		cfg.InitialAdminUserPassword = v
		set("initial-admin-user-password", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"babel", "enabled"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "babel.enabled",
				Source: "--" + n,
			}
		}
		cfg.Babel.Enabled = v
		set("babel.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"babel", "router-id"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "babel.router-id",
				Source: "--" + n,
			}
		}
		cfg.Babel.RouterID = v
		set("babel.router-id", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"olsr"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "olsr",
				Source: "--" + n,
			}
		}
		cfg.OLSR = v
		set("olsr", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"cors-hosts"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "cors-hosts",
				Source: "--" + n,
			}
		}
		cfg.CORSHosts = v
		set("cors-hosts", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"trusted-proxies"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "trusted-proxies",
				Source: "--" + n,
			}
		}
		cfg.TrustedProxies = v
		set("trusted-proxies", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"hibp-api-key"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "hibp-api-key",
				Source: "--" + n,
			}
		}
		cfg.HIBPAPIKey = v
		set("hibp-api-key", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"server-name"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "server-name",
				Source: "--" + n,
			}
		}
		cfg.ServerName = v
		set("server-name", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"supernode"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "supernode",
				Source: "--" + n,
			}
		}
		cfg.Supernode = v
		set("supernode", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"node-ip"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "node-ip",
				Source: "--" + n,
			}
		}
		cfg.NodeIP = v
		set("node-ip", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"latitude"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetFloat64(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "latitude",
				Source: "--" + n,
			}
		}
		cfg.Latitude = v
		set("latitude", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"longitude"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetFloat64(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "longitude",
				Source: "--" + n,
			}
		}
		cfg.Longitude = v
		set("longitude", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"gridsquare"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "gridsquare",
				Source: "--" + n,
			}
		}
		cfg.Gridsquare = v
		set("gridsquare", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"metrics", "enabled"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.enabled",
				Source: "--" + n,
			}
		}
		cfg.Metrics.Enabled = v
		set("metrics.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"metrics", "node-exporter-host"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.node-exporter-host",
				Source: "--" + n,
			}
		}
		cfg.Metrics.NodeExporterHost = v
		set("metrics.node-exporter-host", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"metrics", "port"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.port",
				Source: "--" + n,
			}
		}
		cfg.Metrics.Port = v
		set("metrics.port", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"wireguard", "starting-address"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "wireguard.starting-address",
				Source: "--" + n,
			}
		}
		cfg.Wireguard.StartingAddress = v
		set("wireguard.starting-address", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"wireguard", "starting-port"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetUint16(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "wireguard.starting-port",
				Source: "--" + n,
			}
		}
		cfg.Wireguard.StartingPort = v
		set("wireguard.starting-port", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"session-secret"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "session-secret",
				Source: "--" + n,
			}
		}
		cfg.SessionSecret = v
		set("session-secret", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"lqm", "enabled"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "lqm.enabled",
				Source: "--" + n,
			}
		}
		cfg.LQM.Enabled = v
		set("lqm.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"walker"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "walker",
				Source: "--" + n,
			}
		}
		cfg.Walker = v
		set("walker", configulator.LayerCLI, "--"+n)
	}
	return nil
}
func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "log-level":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.LogLevel = &str
			default:
				return fmt.Errorf("log-level: expected a string, got %v", v.Kind())
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.Port = &val
			default:
				return fmt.Errorf("port: expected a number, got %v", v.Kind())
			}
		case "password-salt":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.PasswordSalt = &str
			default:
				return fmt.Errorf("password-salt: expected a string, got %v", v.Kind())
			}
		case "pprof":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub pProfShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.PProf = &sub
			}
		case "postgres":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub postgresShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.Postgres = &sub
			}
		case "initial-admin-user-password":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.InitialAdminUserPassword = &str
			default:
				return fmt.Errorf("initial-admin-user-password: expected a string, got %v", v.Kind())
			}
		case "babel":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub babelShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.Babel = &sub
			}
		case "olsr":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case 't', 'f':
				b := v.Bool()
				s.OLSR = &b
			default:
				return fmt.Errorf("olsr: expected a bool, got %v", v.Kind())
			}
		case "cors-hosts":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				tok, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != '[' {
					return fmt.Errorf("cors-hosts: expected an array, got %v", tok.Kind())
				}
				out := []string{}
				for dec.PeekKind() != ']' {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != '"' {
						return fmt.Errorf("cors-hosts: expected a string element, got %v", v.Kind())
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.CORSHosts = &out
			}
		case "trusted-proxies":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				tok, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != '[' {
					return fmt.Errorf("trusted-proxies: expected an array, got %v", tok.Kind())
				}
				out := []string{}
				for dec.PeekKind() != ']' {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != '"' {
						return fmt.Errorf("trusted-proxies: expected a string element, got %v", v.Kind())
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.TrustedProxies = &out
			}
		case "hibp-api-key":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.HIBPAPIKey = &str
			default:
				return fmt.Errorf("hibp-api-key: expected a string, got %v", v.Kind())
			}
		case "server-name":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.ServerName = &str
			default:
				return fmt.Errorf("server-name: expected a string, got %v", v.Kind())
			}
		case "supernode":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case 't', 'f':
				b := v.Bool()
				s.Supernode = &b
			default:
				return fmt.Errorf("supernode: expected a bool, got %v", v.Kind())
			}
		case "node-ip":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.NodeIP = &str
			default:
				return fmt.Errorf("node-ip: expected a string, got %v", v.Kind())
			}
		case "latitude":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Float()
				if err != nil {
					return err
				}
				val := num
				s.Latitude = &val
			default:
				return fmt.Errorf("latitude: expected a number, got %v", v.Kind())
			}
		case "longitude":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Float()
				if err != nil {
					return err
				}
				val := num
				s.Longitude = &val
			default:
				return fmt.Errorf("longitude: expected a number, got %v", v.Kind())
			}
		case "gridsquare":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Gridsquare = &str
			default:
				return fmt.Errorf("gridsquare: expected a string, got %v", v.Kind())
			}
		case "metrics":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub metricsShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.Metrics = &sub
			}
		case "wireguard":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub wireguardShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.Wireguard = &sub
			}
		case "session-secret":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.SessionSecret = &str
			default:
				return fmt.Errorf("session-secret: expected a string, got %v", v.Kind())
			}
		case "lqm":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub lQMShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.LQM = &sub
			}
		case "walker":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case 't', 'f':
				b := v.Bool()
				s.Walker = &b
			default:
				return fmt.Errorf("walker: expected a bool, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*configShadow)(nil)

func (s *pProfShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case 't', 'f':
				b := v.Bool()
				s.Enabled = &b
			default:
				return fmt.Errorf("enabled: expected a bool, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*pProfShadow)(nil)

func (s *postgresShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Host = &str
			default:
				return fmt.Errorf("host: expected a string, got %v", v.Kind())
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.Port = &val
			default:
				return fmt.Errorf("port: expected a number, got %v", v.Kind())
			}
		case "user":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.User = &str
			default:
				return fmt.Errorf("user: expected a string, got %v", v.Kind())
			}
		case "password":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Password = &str
			default:
				return fmt.Errorf("password: expected a string, got %v", v.Kind())
			}
		case "database":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Database = &str
			default:
				return fmt.Errorf("database: expected a string, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*postgresShadow)(nil)

func (s *babelShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case 't', 'f':
				b := v.Bool()
				s.Enabled = &b
			default:
				return fmt.Errorf("enabled: expected a bool, got %v", v.Kind())
			}
		case "router-id":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.RouterID = &str
			default:
				return fmt.Errorf("router-id: expected a string, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*babelShadow)(nil)

func (s *metricsShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case 't', 'f':
				b := v.Bool()
				s.Enabled = &b
			default:
				return fmt.Errorf("enabled: expected a bool, got %v", v.Kind())
			}
		case "node-exporter-host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.NodeExporterHost = &str
			default:
				return fmt.Errorf("node-exporter-host: expected a string, got %v", v.Kind())
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.Port = &val
			default:
				return fmt.Errorf("port: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*metricsShadow)(nil)

func (s *wireguardShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "starting-address":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.StartingAddress = &str
			default:
				return fmt.Errorf("starting-address: expected a string, got %v", v.Kind())
			}
		case "starting-port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				if num > math.MaxUint16 {
					return fmt.Errorf("starting-port: %d overflows uint16", num)
				}
				val := uint16(num)
				s.StartingPort = &val
			default:
				return fmt.Errorf("starting-port: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*wireguardShadow)(nil)

func (s *lQMShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case 't', 'f':
				b := v.Bool()
				s.Enabled = &b
			default:
				return fmt.Errorf("enabled: expected a bool, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*lQMShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c *Config) PrintConfig() string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("log-level = %v\n", c.LogLevel))
	b.WriteString(fmt.Sprintf("port = %v\n", c.Port))
	b.WriteString(fmt.Sprintf("password-salt = %v\n", c.PasswordSalt))
	b.WriteString(fmt.Sprintf("pprof.enabled = %v\n", c.PProf.Enabled))
	b.WriteString(fmt.Sprintf("postgres.host = %v\n", c.Postgres.Host))
	b.WriteString(fmt.Sprintf("postgres.port = %v\n", c.Postgres.Port))
	b.WriteString(fmt.Sprintf("postgres.user = %v\n", c.Postgres.User))
	b.WriteString(fmt.Sprintf("postgres.password = %v\n", c.Postgres.Password))
	b.WriteString(fmt.Sprintf("postgres.database = %v\n", c.Postgres.Database))
	b.WriteString(fmt.Sprintf("initial-admin-user-password = %v\n", c.InitialAdminUserPassword))
	b.WriteString(fmt.Sprintf("babel.enabled = %v\n", c.Babel.Enabled))
	b.WriteString(fmt.Sprintf("babel.router-id = %v\n", c.Babel.RouterID))
	b.WriteString(fmt.Sprintf("olsr = %v\n", c.OLSR))
	b.WriteString(fmt.Sprintf("cors-hosts = %v\n", c.CORSHosts))
	b.WriteString(fmt.Sprintf("trusted-proxies = %v\n", c.TrustedProxies))
	b.WriteString(fmt.Sprintf("hibp-api-key = %v\n", c.HIBPAPIKey))
	b.WriteString(fmt.Sprintf("server-name = %v\n", c.ServerName))
	b.WriteString(fmt.Sprintf("supernode = %v\n", c.Supernode))
	b.WriteString(fmt.Sprintf("node-ip = %v\n", c.NodeIP))
	b.WriteString(fmt.Sprintf("latitude = %v\n", c.Latitude))
	b.WriteString(fmt.Sprintf("longitude = %v\n", c.Longitude))
	b.WriteString(fmt.Sprintf("gridsquare = %v\n", c.Gridsquare))
	b.WriteString(fmt.Sprintf("metrics.enabled = %v\n", c.Metrics.Enabled))
	b.WriteString(fmt.Sprintf("metrics.node-exporter-host = %v\n", c.Metrics.NodeExporterHost))
	b.WriteString(fmt.Sprintf("metrics.port = %v\n", c.Metrics.Port))
	b.WriteString(fmt.Sprintf("wireguard.starting-address = %v\n", c.Wireguard.StartingAddress))
	b.WriteString(fmt.Sprintf("wireguard.starting-port = %v\n", c.Wireguard.StartingPort))
	b.WriteString(fmt.Sprintf("session-secret = %v\n", c.SessionSecret))
	b.WriteString(fmt.Sprintf("lqm.enabled = %v\n", c.LQM.Enabled))
	b.WriteString(fmt.Sprintf("walker = %v\n", c.Walker))
	return b.String()
}
