// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package config

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/USA-RedDragon/configulator/v2/impl"
	"github.com/spf13/pflag"
)

type pProfShadow struct {
	Enabled *bool `json:"enabled" toml:"enabled" yaml:"enabled"`
}

type postgresShadow struct {
	Host     *string `json:"host"     toml:"host"     yaml:"host"`
	Port     *int    `json:"port"     toml:"port"     yaml:"port"`
	User     *string `json:"user"     toml:"user"     yaml:"user"`
	Password *string `json:"password" toml:"password" yaml:"password"`
	Database *string `json:"database" toml:"database" yaml:"database"`
}

type babelShadow struct {
	Enabled  *bool   `json:"enabled"   toml:"enabled"   yaml:"enabled"`
	RouterID *string `json:"router-id" toml:"router-id" yaml:"router-id"`
}

type metricsShadow struct {
	Enabled          *bool   `json:"enabled"            toml:"enabled"            yaml:"enabled"`
	NodeExporterHost *string `json:"node-exporter-host" toml:"node-exporter-host" yaml:"node-exporter-host"`
	Port             *int    `json:"port"               toml:"port"               yaml:"port"`
}

type wireguardShadow struct {
	StartingAddress *string `json:"starting-address" toml:"starting-address" yaml:"starting-address"`
	StartingPort    *uint16 `json:"starting-port"    toml:"starting-port"    yaml:"starting-port"`
}

type lQMShadow struct {
	Enabled *bool `json:"enabled" toml:"enabled" yaml:"enabled"`
}

type configShadow struct {
	LogLevel                 *string          `json:"log-level"                   toml:"log-level"                   yaml:"log-level"`
	Port                     *int             `json:"port"                        toml:"port"                        yaml:"port"`
	PasswordSalt             *string          `json:"password-salt"               toml:"password-salt"               yaml:"password-salt"`
	PProf                    *pProfShadow     `json:"pprof"                       toml:"pprof"                       yaml:"pprof"`
	Postgres                 *postgresShadow  `json:"postgres"                    toml:"postgres"                    yaml:"postgres"`
	InitialAdminUserPassword *string          `json:"initial-admin-user-password" toml:"initial-admin-user-password" yaml:"initial-admin-user-password"`
	Babel                    *babelShadow     `json:"babel"                       toml:"babel"                       yaml:"babel"`
	OLSR                     *bool            `json:"olsr"                        toml:"olsr"                        yaml:"olsr"`
	CORSHosts                *[]string        `json:"cors-hosts"                  toml:"cors-hosts"                  yaml:"cors-hosts"`
	TrustedProxies           *[]string        `json:"trusted-proxies"             toml:"trusted-proxies"             yaml:"trusted-proxies"`
	HIBPAPIKey               *string          `json:"hibp-api-key"                toml:"hibp-api-key"                yaml:"hibp-api-key"`
	ServerName               *string          `json:"server-name"                 toml:"server-name"                 yaml:"server-name"`
	Supernode                *bool            `json:"supernode"                   toml:"supernode"                   yaml:"supernode"`
	NodeIP                   *string          `json:"node-ip"                     toml:"node-ip"                     yaml:"node-ip"`
	Latitude                 *float64         `json:"latitude"                    toml:"latitude"                    yaml:"latitude"`
	Longitude                *float64         `json:"longitude"                   toml:"longitude"                   yaml:"longitude"`
	Gridsquare               *string          `json:"gridsquare"                  toml:"gridsquare"                  yaml:"gridsquare"`
	Metrics                  *metricsShadow   `json:"metrics"                     toml:"metrics"                     yaml:"metrics"`
	Wireguard                *wireguardShadow `json:"wireguard"                   toml:"wireguard"                   yaml:"wireguard"`
	SessionSecret            *string          `json:"session-secret"              toml:"session-secret"              yaml:"session-secret"`
	LQM                      *lQMShadow       `json:"lqm"                         toml:"lqm"                         yaml:"lqm"`
	Walker                   *bool            `json:"walker"                      toml:"walker"                      yaml:"walker"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}

func configApplyDefaults(cfg *Config, _ string, set configulator.SetOrigin) error {
	cfg.LogLevel = LogLevel("info")
	set("log-level", configulator.LayerDefault, "default tag")
	cfg.Port = 3333
	set("port", configulator.LayerDefault, "default tag")
	cfg.PProf.Enabled = false
	set("pprof.enabled", configulator.LayerDefault, "default tag")
	cfg.Postgres.Port = 5432
	set("postgres.port", configulator.LayerDefault, "default tag")
	cfg.Babel.Enabled = false
	set("babel.enabled", configulator.LayerDefault, "default tag")
	cfg.OLSR = true
	set("olsr", configulator.LayerDefault, "default tag")
	cfg.Metrics.NodeExporterHost = "node-exporter"
	set("metrics.node-exporter-host", configulator.LayerDefault, "default tag")
	cfg.Metrics.Port = 9100
	set("metrics.port", configulator.LayerDefault, "default tag")
	cfg.Wireguard.StartingPort = uint16(5527)
	set("wireguard.starting-port", configulator.LayerDefault, "default tag")
	cfg.LQM.Enabled = true
	set("lqm.enabled", configulator.LayerDefault, "default tag")
	cfg.Walker = false
	set("walker", configulator.LayerDefault, "default tag")
	return nil
}

func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *configShadow) applyTo(cfg *Config, _ string, set configulator.SetOrigin, file string) error {
	if s.LogLevel != nil {
		cfg.LogLevel = LogLevel(*s.LogLevel)
		set("log-level", configulator.LayerFile, file)
	}
	if s.Port != nil {
		cfg.Port = *s.Port
		set("port", configulator.LayerFile, file)
	}
	if s.PasswordSalt != nil {
		cfg.PasswordSalt = *s.PasswordSalt
		set("password-salt", configulator.LayerFile, file)
	}
	if s.PProf != nil {
		if s.PProf.Enabled != nil {
			cfg.PProf.Enabled = *s.PProf.Enabled
			set("pprof.enabled", configulator.LayerFile, file)
		}
	}
	if s.Postgres != nil {
		if s.Postgres.Host != nil {
			cfg.Postgres.Host = *s.Postgres.Host
			set("postgres.host", configulator.LayerFile, file)
		}
		if s.Postgres.Port != nil {
			cfg.Postgres.Port = *s.Postgres.Port
			set("postgres.port", configulator.LayerFile, file)
		}
		if s.Postgres.User != nil {
			cfg.Postgres.User = *s.Postgres.User
			set("postgres.user", configulator.LayerFile, file)
		}
		if s.Postgres.Password != nil {
			cfg.Postgres.Password = *s.Postgres.Password
			set("postgres.password", configulator.LayerFile, file)
		}
		if s.Postgres.Database != nil {
			cfg.Postgres.Database = *s.Postgres.Database
			set("postgres.database", configulator.LayerFile, file)
		}
	}
	if s.InitialAdminUserPassword != nil {
		cfg.InitialAdminUserPassword = *s.InitialAdminUserPassword
		set("initial-admin-user-password", configulator.LayerFile, file)
	}
	if s.Babel != nil {
		if s.Babel.Enabled != nil {
			cfg.Babel.Enabled = *s.Babel.Enabled
			set("babel.enabled", configulator.LayerFile, file)
		}
		if s.Babel.RouterID != nil {
			cfg.Babel.RouterID = *s.Babel.RouterID
			set("babel.router-id", configulator.LayerFile, file)
		}
	}
	if s.OLSR != nil {
		cfg.OLSR = *s.OLSR
		set("olsr", configulator.LayerFile, file)
	}
	if s.CORSHosts != nil {
		cfg.CORSHosts = *s.CORSHosts
		set("cors-hosts", configulator.LayerFile, file)
	}
	if s.TrustedProxies != nil {
		cfg.TrustedProxies = *s.TrustedProxies
		set("trusted-proxies", configulator.LayerFile, file)
	}
	if s.HIBPAPIKey != nil {
		cfg.HIBPAPIKey = *s.HIBPAPIKey
		set("hibp-api-key", configulator.LayerFile, file)
	}
	if s.ServerName != nil {
		cfg.ServerName = *s.ServerName
		set("server-name", configulator.LayerFile, file)
	}
	if s.Supernode != nil {
		cfg.Supernode = *s.Supernode
		set("supernode", configulator.LayerFile, file)
	}
	if s.NodeIP != nil {
		cfg.NodeIP = *s.NodeIP
		set("node-ip", configulator.LayerFile, file)
	}
	if s.Latitude != nil {
		cfg.Latitude = *s.Latitude
		set("latitude", configulator.LayerFile, file)
	}
	if s.Longitude != nil {
		cfg.Longitude = *s.Longitude
		set("longitude", configulator.LayerFile, file)
	}
	if s.Gridsquare != nil {
		cfg.Gridsquare = *s.Gridsquare
		set("gridsquare", configulator.LayerFile, file)
	}
	if s.Metrics != nil {
		if s.Metrics.Enabled != nil {
			cfg.Metrics.Enabled = *s.Metrics.Enabled
			set("metrics.enabled", configulator.LayerFile, file)
		}
		if s.Metrics.NodeExporterHost != nil {
			cfg.Metrics.NodeExporterHost = *s.Metrics.NodeExporterHost
			set("metrics.node-exporter-host", configulator.LayerFile, file)
		}
		if s.Metrics.Port != nil {
			cfg.Metrics.Port = *s.Metrics.Port
			set("metrics.port", configulator.LayerFile, file)
		}
	}
	if s.Wireguard != nil {
		if s.Wireguard.StartingAddress != nil {
			cfg.Wireguard.StartingAddress = *s.Wireguard.StartingAddress
			set("wireguard.starting-address", configulator.LayerFile, file)
		}
		if s.Wireguard.StartingPort != nil {
			cfg.Wireguard.StartingPort = *s.Wireguard.StartingPort
			set("wireguard.starting-port", configulator.LayerFile, file)
		}
	}
	if s.SessionSecret != nil {
		cfg.SessionSecret = *s.SessionSecret
		set("session-secret", configulator.LayerFile, file)
	}
	if s.LQM != nil {
		if s.LQM.Enabled != nil {
			cfg.LQM.Enabled = *s.LQM.Enabled
			set("lqm.enabled", configulator.LayerFile, file)
		}
	}
	if s.Walker != nil {
		cfg.Walker = *s.Walker
		set("walker", configulator.LayerFile, file)
	}
	return nil
}

func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "log-level"); ok {
		cfg.LogLevel = LogLevel(v)
		set("log-level", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "port",
				Source: n,
				Value:  v,
			}
		}
		cfg.Port = int(p)
		set("port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "password-salt"); ok {
		cfg.PasswordSalt = v
		set("password-salt", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "pprof", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.PProf.Enabled = p
		set("pprof.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "postgres", "host"); ok {
		cfg.Postgres.Host = v
		set("postgres.host", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "postgres", "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "postgres.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.Postgres.Port = int(p)
		set("postgres.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "postgres", "user"); ok {
		cfg.Postgres.User = v
		set("postgres.user", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "postgres", "password"); ok {
		cfg.Postgres.Password = v
		set("postgres.password", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "postgres", "database"); ok {
		cfg.Postgres.Database = v
		set("postgres.database", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "initial-admin-user-password"); ok {
		cfg.InitialAdminUserPassword = v
		set("initial-admin-user-password", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "babel", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "babel.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.Babel.Enabled = p
		set("babel.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "babel", "router-id"); ok {
		cfg.Babel.RouterID = v
		set("babel.router-id", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "olsr"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "olsr",
				Source: n,
				Value:  v,
			}
		}
		cfg.OLSR = p
		set("olsr", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "cors-hosts"); ok {
		lst := impl.SplitList(v, ec.ArraySeparator)
		cfg.CORSHosts = lst
		set("cors-hosts", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "trusted-proxies"); ok {
		lst := impl.SplitList(v, ec.ArraySeparator)
		cfg.TrustedProxies = lst
		set("trusted-proxies", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "hibp-api-key"); ok {
		cfg.HIBPAPIKey = v
		set("hibp-api-key", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "server-name"); ok {
		cfg.ServerName = v
		set("server-name", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "supernode"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "supernode",
				Source: n,
				Value:  v,
			}
		}
		cfg.Supernode = p
		set("supernode", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "node-ip"); ok {
		cfg.NodeIP = v
		set("node-ip", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "latitude"); ok {
		p, err := strconv.ParseFloat(v, 64)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "latitude",
				Source: n,
				Value:  v,
			}
		}
		cfg.Latitude = p
		set("latitude", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "longitude"); ok {
		p, err := strconv.ParseFloat(v, 64)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "longitude",
				Source: n,
				Value:  v,
			}
		}
		cfg.Longitude = p
		set("longitude", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "gridsquare"); ok {
		cfg.Gridsquare = v
		set("gridsquare", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "metrics", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.Metrics.Enabled = p
		set("metrics.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "metrics", "node-exporter-host"); ok {
		cfg.Metrics.NodeExporterHost = v
		set("metrics.node-exporter-host", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "metrics", "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.Metrics.Port = int(p)
		set("metrics.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "wireguard", "starting-address"); ok {
		cfg.Wireguard.StartingAddress = v
		set("wireguard.starting-address", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "wireguard", "starting-port"); ok {
		p, err := strconv.ParseUint(v, 10, 16)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "wireguard.starting-port",
				Source: n,
				Value:  v,
			}
		}
		cfg.Wireguard.StartingPort = uint16(p)
		set("wireguard.starting-port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "session-secret"); ok {
		cfg.SessionSecret = v
		set("session-secret", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "lqm", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "lqm.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.LQM.Enabled = p
		set("lqm.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "walker"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "walker",
				Source: n,
				Value:  v,
			}
		}
		cfg.Walker = p
		set("walker", configulator.LayerEnv, n)
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}

func configRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	names := []string{
		"log-level",
		"port",
		"password-salt",
		"pprof" + o.Separator + "enabled",
		"postgres" + o.Separator + "host",
		"postgres" + o.Separator + "port",
		"postgres" + o.Separator + "user",
		"postgres" + o.Separator + "password",
		"postgres" + o.Separator + "database",
		"initial-admin-user-password",
		"babel" + o.Separator + "enabled",
		"babel" + o.Separator + "router-id",
		"olsr",
		"cors-hosts",
		"trusted-proxies",
		"hibp-api-key",
		"server-name",
		"supernode",
		"node-ip",
		"latitude",
		"longitude",
		"gridsquare",
		"metrics" + o.Separator + "enabled",
		"metrics" + o.Separator + "node-exporter-host",
		"metrics" + o.Separator + "port",
		"wireguard" + o.Separator + "starting-address",
		"wireguard" + o.Separator + "starting-port",
		"session-secret",
		"lqm" + o.Separator + "enabled",
		"walker",
	}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], "info", "Logging level for the application. One of debug, info, warn, or error")
	fs.Var(impl.NewInt(3333), names[1], "Port to listen on for HTTP requests")
	fs.String(names[2], "", "Salt used for password hashing")
	fs.Bool(names[3], false, "Enable pprof debugging")
	fs.String(names[4], "", "PostgreSQL host")
	fs.Var(impl.NewInt(5432), names[5], "PostgreSQL port")
	fs.String(names[6], "", "PostgreSQL user")
	fs.String(names[7], "", "PostgreSQL password")
	fs.String(names[8], "", "PostgreSQL database")
	fs.String(names[9], "", "Initial password for the admin user")
	fs.Bool(names[10], false, "Enable Babel routing")
	fs.String(names[11], "", "Babel router ID")
	fs.Bool(names[12], true, "Enable OLSR routing")
	fs.StringSlice(names[13], nil, "CORS hosts for the API")
	fs.StringSlice(names[14], nil, "Trusted proxies for the API")
	fs.String(names[15], "", "Have I Been Pwned API key")
	fs.String(names[16], "", "Server name")
	fs.Bool(names[17], false, "Enable supernode mode")
	fs.String(names[18], "", "Node IP address")
	fs.Float64(names[19], 0.0, "Server latitude")
	fs.Float64(names[20], 0.0, "Server longitude")
	fs.String(names[21], "", "Server gridsquare")
	fs.Bool(names[22], false, "Enable Prometheus metrics")
	fs.String(names[23], "node-exporter", "Node exporter host for Prometheus metrics")
	fs.Var(impl.NewInt(9100), names[24], "Port for Prometheus metrics")
	fs.String(names[25], "", "Starting address for Wireguard")
	fs.Uint16(names[26], 5527, "Starting port for Wireguard")
	fs.String(names[27], "", "Session secret")
	fs.Bool(names[28], true, "Enable Link Quality Monitoring")
	fs.Bool(names[29], false, "Enable periodic mesh walking to update meshmap")
	return nil
}

func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, o *cpflag.Options, _ string, set configulator.SetOrigin) error {
	if n := "log-level"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "log-level",
				Source: "--" + n,
			}
		}
		cfg.LogLevel = LogLevel(v)
		set("log-level", configulator.LayerCLI, "--"+n)
	}
	if n := "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "port",
				Source: "--" + n,
			}
		}
		cfg.Port = v
		set("port", configulator.LayerCLI, "--"+n)
	}
	if n := "password-salt"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "password-salt",
				Source: "--" + n,
			}
		}
		cfg.PasswordSalt = v
		set("password-salt", configulator.LayerCLI, "--"+n)
	}
	if n := "pprof" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.enabled",
				Source: "--" + n,
			}
		}
		cfg.PProf.Enabled = v
		set("pprof.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "postgres" + o.Separator + "host"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "postgres.host",
				Source: "--" + n,
			}
		}
		cfg.Postgres.Host = v
		set("postgres.host", configulator.LayerCLI, "--"+n)
	}
	if n := "postgres" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "postgres.port",
				Source: "--" + n,
			}
		}
		cfg.Postgres.Port = v
		set("postgres.port", configulator.LayerCLI, "--"+n)
	}
	if n := "postgres" + o.Separator + "user"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "postgres.user",
				Source: "--" + n,
			}
		}
		cfg.Postgres.User = v
		set("postgres.user", configulator.LayerCLI, "--"+n)
	}
	if n := "postgres" + o.Separator + "password"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "postgres.password",
				Source: "--" + n,
			}
		}
		cfg.Postgres.Password = v
		set("postgres.password", configulator.LayerCLI, "--"+n)
	}
	if n := "postgres" + o.Separator + "database"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "postgres.database",
				Source: "--" + n,
			}
		}
		cfg.Postgres.Database = v
		set("postgres.database", configulator.LayerCLI, "--"+n)
	}
	if n := "initial-admin-user-password"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "initial-admin-user-password",
				Source: "--" + n,
			}
		}
		cfg.InitialAdminUserPassword = v
		set("initial-admin-user-password", configulator.LayerCLI, "--"+n)
	}
	if n := "babel" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "babel.enabled",
				Source: "--" + n,
			}
		}
		cfg.Babel.Enabled = v
		set("babel.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "babel" + o.Separator + "router-id"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "babel.router-id",
				Source: "--" + n,
			}
		}
		cfg.Babel.RouterID = v
		set("babel.router-id", configulator.LayerCLI, "--"+n)
	}
	if n := "olsr"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "olsr",
				Source: "--" + n,
			}
		}
		cfg.OLSR = v
		set("olsr", configulator.LayerCLI, "--"+n)
	}
	if n := "cors-hosts"; fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "cors-hosts",
				Source: "--" + n,
			}
		}
		cfg.CORSHosts = v
		set("cors-hosts", configulator.LayerCLI, "--"+n)
	}
	if n := "trusted-proxies"; fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "trusted-proxies",
				Source: "--" + n,
			}
		}
		cfg.TrustedProxies = v
		set("trusted-proxies", configulator.LayerCLI, "--"+n)
	}
	if n := "hibp-api-key"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "hibp-api-key",
				Source: "--" + n,
			}
		}
		cfg.HIBPAPIKey = v
		set("hibp-api-key", configulator.LayerCLI, "--"+n)
	}
	if n := "server-name"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "server-name",
				Source: "--" + n,
			}
		}
		cfg.ServerName = v
		set("server-name", configulator.LayerCLI, "--"+n)
	}
	if n := "supernode"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "supernode",
				Source: "--" + n,
			}
		}
		cfg.Supernode = v
		set("supernode", configulator.LayerCLI, "--"+n)
	}
	if n := "node-ip"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "node-ip",
				Source: "--" + n,
			}
		}
		cfg.NodeIP = v
		set("node-ip", configulator.LayerCLI, "--"+n)
	}
	if n := "latitude"; fs.Changed(n) {
		v, err := fs.GetFloat64(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "latitude",
				Source: "--" + n,
			}
		}
		cfg.Latitude = v
		set("latitude", configulator.LayerCLI, "--"+n)
	}
	if n := "longitude"; fs.Changed(n) {
		v, err := fs.GetFloat64(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "longitude",
				Source: "--" + n,
			}
		}
		cfg.Longitude = v
		set("longitude", configulator.LayerCLI, "--"+n)
	}
	if n := "gridsquare"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "gridsquare",
				Source: "--" + n,
			}
		}
		cfg.Gridsquare = v
		set("gridsquare", configulator.LayerCLI, "--"+n)
	}
	if n := "metrics" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.enabled",
				Source: "--" + n,
			}
		}
		cfg.Metrics.Enabled = v
		set("metrics.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "metrics" + o.Separator + "node-exporter-host"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.node-exporter-host",
				Source: "--" + n,
			}
		}
		cfg.Metrics.NodeExporterHost = v
		set("metrics.node-exporter-host", configulator.LayerCLI, "--"+n)
	}
	if n := "metrics" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.port",
				Source: "--" + n,
			}
		}
		cfg.Metrics.Port = v
		set("metrics.port", configulator.LayerCLI, "--"+n)
	}
	if n := "wireguard" + o.Separator + "starting-address"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "wireguard.starting-address",
				Source: "--" + n,
			}
		}
		cfg.Wireguard.StartingAddress = v
		set("wireguard.starting-address", configulator.LayerCLI, "--"+n)
	}
	if n := "wireguard" + o.Separator + "starting-port"; fs.Changed(n) {
		v, err := fs.GetUint16(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "wireguard.starting-port",
				Source: "--" + n,
			}
		}
		cfg.Wireguard.StartingPort = v
		set("wireguard.starting-port", configulator.LayerCLI, "--"+n)
	}
	if n := "session-secret"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "session-secret",
				Source: "--" + n,
			}
		}
		cfg.SessionSecret = v
		set("session-secret", configulator.LayerCLI, "--"+n)
	}
	if n := "lqm" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "lqm.enabled",
				Source: "--" + n,
			}
		}
		cfg.LQM.Enabled = v
		set("lqm.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "walker"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "walker",
				Source: "--" + n,
			}
		}
		cfg.Walker = v
		set("walker", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected an object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "log-level":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.LogLevel = &str
			default:
				return configJSONError("log-level", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError("port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError("port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError("port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "password-salt":
			if err := func() error {
				v, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch v.Kind() {
				case jsontext.KindNull:
				case jsontext.KindString:
					str := v.String()
					s.PasswordSalt = &str
				default:
					return configJSONError("password-salt", v, fmt.Errorf("expected a string, got %v", v.Kind()))
				}
				return nil
			}(); err != nil {
				return &configulator.ParseError{
					Err:   errors.New("invalid value"),
					Path:  "password-salt",
					Value: "(redacted)",
				}
			}
		case "pprof":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("pprof", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub pProfShadow
				if err := sub.decodeJSON(dec, "pprof"); err != nil {
					return err
				}
				s.PProf = &sub
			}
		case "postgres":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("postgres", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub postgresShadow
				if err := sub.decodeJSON(dec, "postgres"); err != nil {
					return err
				}
				s.Postgres = &sub
			}
		case "initial-admin-user-password":
			if err := func() error {
				v, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch v.Kind() {
				case jsontext.KindNull:
				case jsontext.KindString:
					str := v.String()
					s.InitialAdminUserPassword = &str
				default:
					return configJSONError("initial-admin-user-password", v, fmt.Errorf("expected a string, got %v", v.Kind()))
				}
				return nil
			}(); err != nil {
				return &configulator.ParseError{
					Err:   errors.New("invalid value"),
					Path:  "initial-admin-user-password",
					Value: "(redacted)",
				}
			}
		case "babel":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("babel", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub babelShadow
				if err := sub.decodeJSON(dec, "babel"); err != nil {
					return err
				}
				s.Babel = &sub
			}
		case "olsr":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.OLSR = &b
			default:
				return configJSONError("olsr", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "cors-hosts":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginArray {
					return configJSONError("cors-hosts", open, fmt.Errorf("expected an array, got %v", open.Kind()))
				}
				out := []string{}
				for dec.PeekKind() != jsontext.KindEndArray {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != jsontext.KindString {
						return configJSONError("cors-hosts"+"["+strconv.Itoa(len(out))+"]", v, fmt.Errorf("expected a string, got %v", v.Kind()))
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.CORSHosts = &out
			}
		case "trusted-proxies":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginArray {
					return configJSONError("trusted-proxies", open, fmt.Errorf("expected an array, got %v", open.Kind()))
				}
				out := []string{}
				for dec.PeekKind() != jsontext.KindEndArray {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != jsontext.KindString {
						return configJSONError("trusted-proxies"+"["+strconv.Itoa(len(out))+"]", v, fmt.Errorf("expected a string, got %v", v.Kind()))
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.TrustedProxies = &out
			}
		case "hibp-api-key":
			if err := func() error {
				v, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch v.Kind() {
				case jsontext.KindNull:
				case jsontext.KindString:
					str := v.String()
					s.HIBPAPIKey = &str
				default:
					return configJSONError("hibp-api-key", v, fmt.Errorf("expected a string, got %v", v.Kind()))
				}
				return nil
			}(); err != nil {
				return &configulator.ParseError{
					Err:   errors.New("invalid value"),
					Path:  "hibp-api-key",
					Value: "(redacted)",
				}
			}
		case "server-name":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.ServerName = &str
			default:
				return configJSONError("server-name", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "supernode":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Supernode = &b
			default:
				return configJSONError("supernode", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "node-ip":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.NodeIP = &str
			default:
				return configJSONError("node-ip", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "latitude":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				num, err := v.Float()
				if err != nil {
					return configJSONError("latitude", v, err)
				}
				s.Latitude = &num
			default:
				return configJSONError("latitude", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "longitude":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				num, err := v.Float()
				if err != nil {
					return configJSONError("longitude", v, err)
				}
				s.Longitude = &num
			default:
				return configJSONError("longitude", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "gridsquare":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Gridsquare = &str
			default:
				return configJSONError("gridsquare", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "metrics":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("metrics", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub metricsShadow
				if err := sub.decodeJSON(dec, "metrics"); err != nil {
					return err
				}
				s.Metrics = &sub
			}
		case "wireguard":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("wireguard", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub wireguardShadow
				if err := sub.decodeJSON(dec, "wireguard"); err != nil {
					return err
				}
				s.Wireguard = &sub
			}
		case "session-secret":
			if err := func() error {
				v, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch v.Kind() {
				case jsontext.KindNull:
				case jsontext.KindString:
					str := v.String()
					s.SessionSecret = &str
				default:
					return configJSONError("session-secret", v, fmt.Errorf("expected a string, got %v", v.Kind()))
				}
				return nil
			}(); err != nil {
				return &configulator.ParseError{
					Err:   errors.New("invalid value"),
					Path:  "session-secret",
					Value: "(redacted)",
				}
			}
		case "lqm":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("lqm", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub lQMShadow
				if err := sub.decodeJSON(dec, "lqm"); err != nil {
					return err
				}
				s.LQM = &sub
			}
		case "walker":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Walker = &b
			default:
				return configJSONError("walker", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

var _ json.UnmarshalerFrom = (*configShadow)(nil)

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *pProfShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *postgresShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Host = &str
			default:
				return configJSONError(path+".host", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "user":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.User = &str
			default:
				return configJSONError(path+".user", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "password":
			if err := func() error {
				v, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch v.Kind() {
				case jsontext.KindNull:
				case jsontext.KindString:
					str := v.String()
					s.Password = &str
				default:
					return configJSONError(path+".password", v, fmt.Errorf("expected a string, got %v", v.Kind()))
				}
				return nil
			}(); err != nil {
				return &configulator.ParseError{
					Err:   errors.New("invalid value"),
					Path:  path + ".password",
					Value: "(redacted)",
				}
			}
		case "database":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Database = &str
			default:
				return configJSONError(path+".database", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *babelShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "router-id":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.RouterID = &str
			default:
				return configJSONError(path+".router-id", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *metricsShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "node-exporter-host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.NodeExporterHost = &str
			default:
				return configJSONError(path+".node-exporter-host", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *wireguardShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "starting-address":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.StartingAddress = &str
			default:
				return configJSONError(path+".starting-address", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "starting-port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Uint()
				if err != nil {
					return configJSONError(path+".starting-port", v, err)
				}
				if raw > math.MaxUint16 {
					return configJSONError(path+".starting-port", v, fmt.Errorf("%d overflows uint16", raw))
				}
				num := uint16(raw)
				s.StartingPort = &num
			default:
				return configJSONError(path+".starting-port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *lQMShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// configJSONError returns a ParseError for the JSON token v at path.
func configJSONError(path string, v jsontext.Token, err error) error {
	return &configulator.ParseError{
		Err:   err,
		Path:  path,
		Value: v.String(),
	}
}

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c Config) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "log-level = %v\n", c.LogLevel)
	fmt.Fprintf(&b, "port = %v\n", c.Port)
	b.WriteString("password-salt = (redacted)\n")
	fmt.Fprintf(&b, "pprof.enabled = %v\n", c.PProf.Enabled)
	fmt.Fprintf(&b, "postgres.host = %v\n", c.Postgres.Host)
	fmt.Fprintf(&b, "postgres.port = %v\n", c.Postgres.Port)
	fmt.Fprintf(&b, "postgres.user = %v\n", c.Postgres.User)
	b.WriteString("postgres.password = (redacted)\n")
	fmt.Fprintf(&b, "postgres.database = %v\n", c.Postgres.Database)
	b.WriteString("initial-admin-user-password = (redacted)\n")
	fmt.Fprintf(&b, "babel.enabled = %v\n", c.Babel.Enabled)
	fmt.Fprintf(&b, "babel.router-id = %v\n", c.Babel.RouterID)
	fmt.Fprintf(&b, "olsr = %v\n", c.OLSR)
	fmt.Fprintf(&b, "cors-hosts = %v\n", c.CORSHosts)
	fmt.Fprintf(&b, "trusted-proxies = %v\n", c.TrustedProxies)
	b.WriteString("hibp-api-key = (redacted)\n")
	fmt.Fprintf(&b, "server-name = %v\n", c.ServerName)
	fmt.Fprintf(&b, "supernode = %v\n", c.Supernode)
	fmt.Fprintf(&b, "node-ip = %v\n", c.NodeIP)
	fmt.Fprintf(&b, "latitude = %v\n", c.Latitude)
	fmt.Fprintf(&b, "longitude = %v\n", c.Longitude)
	fmt.Fprintf(&b, "gridsquare = %v\n", c.Gridsquare)
	fmt.Fprintf(&b, "metrics.enabled = %v\n", c.Metrics.Enabled)
	fmt.Fprintf(&b, "metrics.node-exporter-host = %v\n", c.Metrics.NodeExporterHost)
	fmt.Fprintf(&b, "metrics.port = %v\n", c.Metrics.Port)
	fmt.Fprintf(&b, "wireguard.starting-address = %v\n", c.Wireguard.StartingAddress)
	fmt.Fprintf(&b, "wireguard.starting-port = %v\n", c.Wireguard.StartingPort)
	b.WriteString("session-secret = (redacted)\n")
	fmt.Fprintf(&b, "lqm.enabled = %v\n", c.LQM.Enabled)
	fmt.Fprintf(&b, "walker = %v\n", c.Walker)
	return b.String()
}

func configQuoteKey(k string) string {
	if strings.ContainsAny(k, ".[") {
		return "\"" + strings.NewReplacer("\\", "\\\\", "\"", "\\\"").Replace(k) + "\""
	}
	return k
}
