name: Release

on:
  push:
    tags:
      - "v*"

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: false

jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: write
    uses: USA-RedDragon/reusable-actions/.github/workflows/goreleaser.yaml@6271608d4971ff34aa8b1c3ad4c61400c061e30d # v2.0.23
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
