name: Release

on:
  push:
    tags:
      - "v*"

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: false

jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: write
    uses: USA-RedDragon/reusable-actions/.github/workflows/goreleaser.yaml@c7f24b7a3dc1110838186b173b1f1a2a65ff1c91 # v2.0.22
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
